# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b34b3cc48901fa60653529190de44d4"
name = "wishlist-go-backend"
application_url = "https://gizug0-vd.myshopify.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_customers,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[app_proxy]
url="https://gizug0-vd.myshopify.com/"
prefix="apps"
subpath="wishlist"

[auth]
redirect_urls = [ ]
